### ISSUE TITLE
Not sure if alpha is supposed to be in a working state right now or not but getting these errors upon logging in..

### ISSUE THREAD

**Issue by JourneyOver** [erglo/wow-handynotes-loremaster#1]
Downloaded the addon to check it out and all that (I Know it's in alpha stages atm).. but upon loading in or doing a `/reload` I get errors (10 of them to be exact):

Error 1:
```lua
Message: Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:2 Error loading Interface/AddOns/HandyNotes_erglo_Loremaster/libs/LibStub/LibStub.lua
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 2:
```lua
Message: Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:3 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceAddon-3.0/AceAddon-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 3:
```lua
Message: Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:4 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceConsole-3.0/AceConsole-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 4:
```lua
Message: Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:5 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceDB-3.0/AceDB-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 5:
```lua
Message: Interface\FrameXML\Bindings.xml:26 Error loading Interface/AddOns/HandyNotes_erglo_Loremaster/utils/achievements.lua
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 6:
```lua
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:2 Error loading Interface/AddOns/HandyNotes_erglo_Loremaster/libs/LibStub/LibStub.lua
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 7:
```lua
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:3 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceAddon-3.0/AceAddon-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 8:
```lua
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:4 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceConsole-3.0/AceConsole-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 9:
```lua
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_erglo_Loremaster/embeds.xml:5 Couldn't open Interface/AddOns/HandyNotes_erglo_Loremaster/libs/AceDB-3.0/AceDB-3.0.xml
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

Error 10:
```lua
Message: Interface\FrameXML\Bindings.xml:1 Interface\FrameXML\Bindings.xml:26 Error loading Interface/AddOns/HandyNotes_erglo_Loremaster/utils/achievements.lua
Time: Wed Sep 20 15:40:29 2023
Count: 1
```

**Comment by erglo** [comment]
Hi, thank you for reporting this.
It seems that the external libraries couldn't be loaded.
While releasing the first version (`v0.1.0-alpha`) an error occurred during packaging and the addon was released without including the external libraries. As soon as I realised this mishap I released a corrected package (`v0.1.1-alpha`) with all libraries included.

Please check which version you are using, also please tell me from where you download the addon.
I will check the package from the download source as soon as possible.

BTW, yes this is supposed to be a playable version, but I am at a very early development stage and I am still trying different things out in order to see which possibilities I have, hence the `alpha` status.
Thanks for trying it out!

**Comment by JourneyOver** [comment]
@erglo I was downloading it from [curseforge](https://www.curseforge.com/wow/addons/handynotes-loremaster) and downloaded version `v0.1.1-alpha`

I did just go and redownload the addon (as I had deleted it after making the report until you got back to me) again and I decided to check in the lib folders, and all the folders inside the lib folder is are all empty so I am guessing even `v0.1.1-alpha` had an issue with packaging the external libraries as well.

Edit: Just checked and your releases on github also have the same problem of empty lib folders for `v0.1.1-alpha`

Edit2: also just checked your github action, and seen that there should of been a `utils` folder in as well with stuff from `https://github.com/erglo/wow-addon-utilities` inside that folder.. but it seems that folder is completely missing.

**Comment by erglo** [comment]
Thanks for your answer and for double checking the content of the packages.
I was sure I fixed that problem, but I must have overlooked something.
I'll check this again and re-upload the addon as soon as I get home.

**Comment by erglo** [comment]
Hi @JourneyOver! I fixed this problem, double-checked everything and released a new version.
It should work now. Please tell me, if there are still any errors.
Thank you again for reporting this problem.

**Comment by JourneyOver** [comment]
@erglo so far so good, looks like everything is now included correctly and so far no errors have come up.
