### ISSUE TITLE
Tooltip starts flickering

### ISSUE THREAD

**Issue by Mike160770** [erglo/wow-handynotes-loremaster#5]
When hovering with the mous over the symbol of a WQ or a quest symbol on the world map the tooltip starts to flicker.
That makes it nearly impossible to read the tooltip

**Comment by erglo** [comment]
Hi, thank you for reporting this!
Currently I don't encounter any problems. Could you please provide more details?
Here are some examples:
* Where does this happen, eg. only in TWW zones or in others as well?
* Which tooltip content/categories are active, eg. zone stories, with or without questlines, etc.?
* Does this also happen with active quests?Their type is similar to world quests. Blizzard refreshes their content nonstop in contrast to quest offers which are static.
* Try deactivating all other addons and see if the problem still occurs. 

Anything you can provide can help identifying the problem.

**Comment by Mike160770** [comment]
It could be an issue when using the Mapster addon in combination - I will check this.

Update: tried on another pc with all HandyNotes plug-ins, Mapster, Angrier WQ activated - did not encounter any troubles.
This is getting really strange, so I do not know what is causing all this on my other PC. Anyway - thx four your feedback.

Greetings

**Comment by erglo** [comment]
Thank you as well for your feedback!
